### PR TITLE
877940: Switching of views is not working in documentation of preview sample.

### PR DESCRIPTION
**Pull request by suba-1997**
877940: Switching of views is not working in documentation of preview sample.

### CODE REVIEW

**Review by keerthanaRajendran — APPROVED** [review]

**Comment by suba-1997** [comment]
rebuild

**Comment by suba-1997** [comment]
rebuild

**Comment by suba-1997** [comment]
rebuild

**Comment by suba-1997** [comment]
rebuild

**Comment by keerthanaRajendran** [comment]
rebuild

**Pull request merged**
